r"""lob.py -- LOBRecorder: a non-invasive observer of the limit order book.

Why a recorder at all: ``marketsim`` keeps only ``matched_orders`` (the trade tape) and a
midprice list. The *book* state -- quotes, depth, who is resting where -- is thrown away as
the simulation advances, but Part 2 detection (and any market-quality claim about wash
trading: spread, depth, price impact) needs it. So v2 snapshots the book on every cleared
timestep and can dump it to disk.

Two guarantees this class is built around:

  * **Non-invasive.** It only reads the four-heap's unmatched queues and the already-cached
    fundamental values. In particular it NEVER calls ``get_fundamental_value()``: the
    fundamental is lazily generated with fresh torch draws, so asking for a value at a
    timestep nobody else asked for would change the random path. If the value at t has not
    been generated by an agent, the recorder reports the last generated one and flags it
    (``fund_stale``) instead of forcing a draw.

  * **Sampled on clears, not on every t.** The book only changes when ``market.step()`` runs,
    which upstream only does on timesteps with an arrival (or, here, a wash leg). Rows are
    therefore event-sampled; ``analysis.lob_full_index()`` forward-fills them to a dense
    0..T index when a per-timestep series is wanted.

Row semantics (one row per cleared timestep):
  * ``*_pre``  -- the resting book as inherited at the START of the step, before this step's
                  orders are inserted and before the clear.
  * ``*_post`` -- the resting book AFTER the clear (matched orders are gone).
  * clear/volume columns describe the trades printed in this step's batch clear.
"""
import math

import pandas as pd


def _f(x):
    """+-inf -> NaN (so the columns stay numeric and plot cleanly)."""
    return float("nan") if (x is None or math.isinf(x)) else float(x)


class LOBRecorder:
    def __init__(self, wash_ids=(), depth_levels: int = 5, enabled: bool = True):
        self.wash_ids = set(wash_ids)
        self.depth_levels = int(depth_levels)
        self.enabled = bool(enabled)
        self.rows = []      # per-step snapshots
        self.levels = []    # long-format top-K depth (only if depth_levels > 0)

    # -- book reading -------------------------------------------------------- #
    @staticmethod
    def _side(queue, is_bid: bool):
        """Aggregate one unmatched side into (best, total_qty, n_orders, [(price, qty, n), ...])
        with levels sorted best-first."""
        by_price = {}
        total = 0.0
        n_orders = 0
        for order in queue.order_dict.values():
            p = float(order.price)
            q = float(order.quantity)
            if q <= 0:
                continue
            agg = by_price.setdefault(p, [0.0, 0])
            agg[0] += q
            agg[1] += 1
            total += q
            n_orders += 1
        levels = sorted(((p, v[0], v[1]) for p, v in by_price.items()),
                        key=lambda x: x[0], reverse=is_bid)
        best = levels[0][0] if levels else (-math.inf if is_bid else math.inf)
        return best, total, n_orders, levels

    def book_state(self, market):
        """Snapshot of the resting (unmatched) book right now. Safe to call at any time."""
        ob = market.order_book
        bb, bq, bn, blv = self._side(ob.buy_unmatched, is_bid=True)
        ba, aq, an, alv = self._side(ob.sell_unmatched, is_bid=False)
        mid = 0.5 * (bb + ba) if not (math.isinf(bb) or math.isinf(ba)) else math.nan
        spread = (ba - bb) if not (math.isinf(bb) or math.isinf(ba)) else math.nan
        return dict(best_bid=bb, best_ask=ba, mid=mid, spread=spread,
                    bid_depth=bq, ask_depth=aq, n_bid_orders=bn, n_ask_orders=an,
                    bid_levels=blv, ask_levels=alv)

    @staticmethod
    def _fundamental_cached(market, t):
        """Fundamental at t WITHOUT triggering a lazy draw. Returns (value, is_stale)."""
        fv = getattr(market.fundamental, "fundamental_values", None)
        if not fv:
            return math.nan, True
        if t in fv:
            return float(fv[t]), False
        prior = [k for k in fv if k <= t]
        if not prior:
            return math.nan, True
        return float(fv[max(prior)]), True

    # -- recording ----------------------------------------------------------- #
    def record(self, market, t, pre, new_matched, posts=(), controller=None):
        """Append the snapshot for the timestep t that has just cleared.

        ``pre`` is the ``book_state`` captured before this step's orders were injected.
        """
        if not self.enabled:
            return
        post = self.book_state(market)

        n_legs = len(new_matched)
        volume = sum(float(mo.order.quantity) for mo in new_matched) / 2.0
        clear_price = float(new_matched[0].price) if new_matched else math.nan
        wash_legs = sum(1 for mo in new_matched if mo.order.agent_id in self.wash_ids)

        fund, stale = self._fundamental_cached(market, t)

        wash_phase = ""
        event_idx = -1
        if posts and controller is not None:
            oids = [o.order_id for _, o in posts]
            meta = controller.oid_meta.get(oids[0], {})
            event_idx = meta.get("event_idx", -1)
            legs = {controller.oid_meta.get(o, {}).get("leg") for o in oids}
            wash_phase = "both" if legs == {1, 2} else ("open" if legs == {1} else "close")

        self.rows.append(dict(
            time=t,
            best_bid_pre=_f(pre["best_bid"]), best_ask_pre=_f(pre["best_ask"]),
            mid_pre=_f(pre["mid"]), spread_pre=_f(pre["spread"]),
            bid_depth_pre=pre["bid_depth"], ask_depth_pre=pre["ask_depth"],
            n_bid_orders_pre=pre["n_bid_orders"], n_ask_orders_pre=pre["n_ask_orders"],
            best_bid=_f(post["best_bid"]), best_ask=_f(post["best_ask"]),
            mid=_f(post["mid"]), spread=_f(post["spread"]),
            bid_depth=post["bid_depth"], ask_depth=post["ask_depth"],
            n_bid_orders=post["n_bid_orders"], n_ask_orders=post["n_ask_orders"],
            fundamental=fund, fund_stale=stale,
            clear_price=clear_price, n_matched_legs=n_legs, volume=volume,
            wash_legs=wash_legs, wash_phase=wash_phase, wash_event_idx=event_idx,
        ))

        if self.depth_levels > 0:
            for side, key in (("bid", "bid_levels"), ("ask", "ask_levels")):
                for lvl, (p, q, n) in enumerate(post[key][:self.depth_levels]):
                    self.levels.append(dict(time=t, side=side, level=lvl,
                                            price=float(p), qty=float(q), n_orders=int(n)))

    # -- export -------------------------------------------------------------- #
    def snapshots_df(self) -> pd.DataFrame:
        cols = ["time",
                "best_bid_pre", "best_ask_pre", "mid_pre", "spread_pre",
                "bid_depth_pre", "ask_depth_pre", "n_bid_orders_pre", "n_ask_orders_pre",
                "best_bid", "best_ask", "mid", "spread",
                "bid_depth", "ask_depth", "n_bid_orders", "n_ask_orders",
                "fundamental", "fund_stale", "clear_price", "n_matched_legs", "volume",
                "wash_legs", "wash_phase", "wash_event_idx"]
        return pd.DataFrame(self.rows, columns=cols)

    def levels_df(self) -> pd.DataFrame:
        return pd.DataFrame(self.levels, columns=["time", "side", "level",
                                                  "price", "qty", "n_orders"])
